### ISSUE TITLE
Error using relation in searchBy

### ISSUE THREAD

**Issue by rodr7go** [Gustavinho/laravel-views#102]
Error appears when you try to search using a relation:

`public $searchBy = ['name', 'email', 'address', 'user.buildings']`

Error:
BadMethodCallException
Call to undefined method App\Models\User::user()

i hope there´s an answer, thanks

**Comment by Gustavinho** [comment]
Hi @rodr7go  the search is trying to find a `user` relationship inside the model for this table view, which is `User`, and you don't have that relationship defined `user -> user`, if you are trying to search for something in the `buildings` table related to the users, you can define the `$searchBy` like `['buildings.field_name_to_search_by']` where `buildings` is the name of your relationship in the `User` model.

```
    // App\Models\User.php
    public function buildings()
    {
        return $this->hasMany(BuildingsModel::class);
    }
```
