### ISSUE TITLE
Too many JS

### ISSUE THREAD

**Issue by elfeffe** [Gustavinho/laravel-views#106]
I think the package loads too many JS.
Is jQuery really needed?
Alpinejs is already installed in my system, it's better to add information in the documentation to say how to add it from a CDN, instead of loading it twice.

**Comment by Gustavinho** [comment]
Thanks @elfeffe  I'll take a look at the JS dependencies

**Comment by Gustavinho** [comment]
Hi @elfeffe, as you pointed out, there were some unused JS resources (like jQuery), I removed them from the final JS build, I also added a feature to not load Alpine by default so we can add it manually on our own. I'm just running some final tests to release this

**Comment by Gustavinho** [comment]
Hi @elfeffe, I removed the extra JS resources in the latest release, I'll close this issue
