### ISSUE TITLE
General Modal System

### ISSUE THREAD

**Issue by elfeffe** [Gustavinho/laravel-views#108]
I think you should add a modals system.
Like https://philo.dev/laravel-modals-with-livewire/

I would use it for HTML editing https://github.com/Gustavinho/laravel-views/pull/107

But it can also let us create actions with modals (even child modals), that will be really flexible.

**Comment by Gustavinho** [comment]
yeah @elfeffe, modal actions feature is on the roadmap actually, that will be a great one

![image](https://user-images.githubusercontent.com/4228757/119859922-71b90c00-bedb-11eb-8e9f-ff8088073947.png)

**Comment by elfeffe** [comment]
Ok, I have to work on it, I will send a PR when I have my version to see if it fits your idea.

**Comment by Gustavinho** [comment]
I have some work done on another project, something like this

```php
class ChangeOrderDeliveryDate extends ModalAction
{
    /**
     * Any title you want to be displayed
     * @var String
     * */
    public $title = "Action title";

    /**
     * This should be a valid Feather icon string
     * @var String
     */
    public $icon = "update";

   /** Component to be displayed on the modal */
    public function component()
    {
        return 'components.users.update';
    }

   /** Props passed to the component on the modal */
    public function data(User $user)
    {
        return ['user' => $user];
    }
}
```

They are defined like the current actions, but they display a component on a modal. This `ModalAction` extends the base `Action` class to set the component, the props, and the flag to open the modal.

To close the modal from the component to be rendered on it we can emit a Livewire event to the parent component

That is how it works overall

**Comment by elfeffe** [comment]
I think we are speaking about two different things.

Yes, actions with modals will be great, and I can work on them, we can discuss it on a separate issue because I'm not sure if they are actually actions, they just open a component that does the task.

In any case, we need to define a Modals system, because I want to add HTML editing with a modal, but in that case, I will require https://github.com/livewire-ui/modal for modals, so I ask if it's ok or you want to develop your own system for modals.

I think the best is to add https://github.com/livewire-ui/modal as a requirement, and then use it for modals, for HTML editing in my case, and for Actions with modals, which are a different thing.

I will open a new issue for Actions with Modals.

Please confirm if https://github.com/livewire-ui/modal is okay for you, and I will develop my HTML editing inside a modal to send the PR.

**Comment by Gustavinho** [comment]
I think using https://github.com/livewire-ui/modal is a great option, so far this package doesn't have any other PHP dependency but Livewire, however, I really liked this one, I think it is a good option, we can try it out and see how it goes, with my original plan to fire modal actions we can also use this one to open the modals.

About the HTML editing on a modal, I think I'm not getting what you would like to do, that modal should display a form with a text area (rich text editor) to edit the HTML right? so that is a component being displayed on a modal, maybe there's something that I'm not getting

**Comment by elfeffe** [comment]
Yes, I just want to open a modal with an editor inside.
The thing is that the "Modals System" must be a generic option, I don't want to use livewire-ui if you are going to develop a new modal, a different one.
I just want to have some consistency and use the same modal system always.
We will probably have to replace the confirm Modal, for example.

So, it will use the same Modal System as the Actions, but I'm not speaking about Actions now, this is just a Pop-Up with an editor, inside a Modal.

I'm checking livewire-ui, I'm not sure it perfectly fits my needs, I'm having some problems that I'm trying to fix.
