### ISSUE TITLE
Table Row Borders

### ISSUE THREAD

**Issue by df999** [Gustavinho/laravel-views#119]
Hey there - any idea why sometimes the gray table row borders are two pixels high instead of one?

See attached image for what I mean (look closely). It's strange that the row it starts on is random, but it's always four rows where it repeats. If I refresh the page, it stays the same every time, but different views have the 2px height start at different rows.

I'm on Windows 10 and it's only doing it in Google Chrome (I just upgraded Chrome to 91.0.4472.114 and both this one and previous version have the issue) - not Firefox or Edge however.

From this page:
https://laravelviews.com/table-view?sortOrder=asc
![table borders](https://user-images.githubusercontent.com/3520592/122694936-feba6100-d20c-11eb-8c2a-52a4e8efc89d.jpg)

I don't have the paged zoomed in. It's 100% zoom.

Is anyone able to reproduce it? It's not a show stopper, but what a strange bug...

**Comment by Gustavinho** [comment]
Hi @df999 , I've never seen this behavior before, have you watch the code on the developer tools? could I see some screenshots of that? of the HTML for one of those rows and also the styles for the `border-b` class on that row?

**Comment by df999** [comment]
Hmm - I just tried it on another Windows 10 / Chrome machine and it does not happen actually. There is obviously something strange with my local Chrome install going on. The HTML is the same (it's right off the demo website). Again it's really weird, but don't worry about it. I have no idea what you could even try anyhow.

Thanks!
