### ISSUE TITLE
test-packages.test

### ISSUE THREAD

**Issue by elfeffe** [Gustavinho/laravel-views#12]
Wrong URL's
` public function js()
    {
        return \Livewire\Livewire::scripts()."\n".
            '<script src="http://test-packages.test/vendor/laravel-views.js" type="text/javascript"></script>';
    }`
`public function css()
    {
        return \Livewire\Livewire::styles()."\n"
            .'<link rel="stylesheet" href="http://test-packages.test/vendor/laravel-views.css" />';
    }`

**Comment by Gustavinho** [comment]
Tanks for raising this issue, I already released a hotfix for this in [1.0.2](https://github.com/Gustavinho/laravel-views/releases/tag/v1.0.2)
