### ISSUE TITLE
Doesn't work with AlpineJS 3

### ISSUE THREAD

**Issue by elfeffe** [Gustavinho/laravel-views#121]
I have this error only if I replace AlpineJS with the version 3, and I include Laravel Views Script
```
livewire.js?id=e6704f81026a73a52725:1 Uncaught RangeError: Maximum call stack size exceeded.
    at dispatch (livewire.js?id=e6704f81026a73a52725:1)
    at Livewire.value (livewire.js?id=e6704f81026a73a52725:13)
    at posts:4745
    at F (cdn.min.js:5)
    at Object.$t [as start] (cdn.min.js:5)
    at laravel-views.js:2
    at posts:4737
    at dispatch (livewire.js?id=e6704f81026a73a52725:1)
    at Livewire.value (livewire.js?id=e6704f81026a73a52725:13)
    at posts:4745
```

**Comment by Gustavinho** [comment]
Hi @elfeffe, the current version is not compatible with Alpine 3, there is a work in progress for that in the next version that I'm already testing, 2.3.0 is still loading Alpine 2 by default but is compatible with version 3 and you will be able to disable the local alpine script to avoid loading twice or use a different version.

btw, I faced some issues using Alpine 3 until I updated the Livewire version, I was having something like `Cannot read property ‘$wire’ of undefined`, once I updated the Livewire version I was able to use alpine 3
