### ISSUE TITLE
Documentation has a lot of issues

### ISSUE THREAD

**Issue by elfeffe** [Gustavinho/laravel-views#128]
This is not the first time that happens, the links are broken.
https://github.com/Gustavinho/laravel-views/blob/master/doc/laravel-views#including-assets

Your package is great, but the people who see it for the first time may think it's abandoned since it has links that take to error 404 pages.

**Comment by Gustavinho** [comment]
Hi @elfeffe thanks for your feedback, yes I'm aware of that, I know the documentation has a lot of typos, issues, etc, and there is a lot of room for improvements, I will keep working to improve the docs
