### ISSUE TITLE
Automate single view for mutiple table like : UserType, CompanyType.

### ISSUE THREAD

**Issue by var2611** [Gustavinho/laravel-views#137]
Hi is there any way to achive so that I can use single class like 
TypeTableView.php ext TableView and send parameterized model and click action so that I can use it for multiple tables.

To achive that need to change create function  parameter which is take class name but if we use object of the class and can extract name from it too.

`function createList(LaravelViews $laravelViews, string $className, string $title, string $sidemenuName, bool $refresh_page = false): string
    {
        $laravelViews
            ->create(**$className**)
            ->layout('main-list', 'container', [
                'title' => $title,
                'refresh' => $refresh_page,
                $sidemenuName => true,
            ]);

        return $laravelViews->render();
    }`

need to change **$classname** to class object of **TypeTableView**.

**Comment by Gustavinho** [comment]
Hi @var2611 you should be able to do that, you can create your own table views extending the original `TableView` class, if you want to have a dynamic class model so you can use the same table for multiple tables you could something like this

```php
class TypeTableview extends TableView {
    public $className;

    protected function repository()
    {
        // This $className would received as a prop of the component, it should be a model class
        return $className::query();
    }
}
```

then you could render the component with the model class name as a prop

```
<livewire:type-table-view className="App\Models\User" />
```

**Comment by var2611** [comment]
Okay Thanks for the Reply it worked. Great.
