### ISSUE TITLE
Inline Editing Issue.

### ISSUE THREAD

**Issue by var2611** [Gustavinho/laravel-views#138]
After pressing error It's showing this error.

The requested resource /livewire/message/type-list.list-user-role was not found on this server.

![image](https://user-images.githubusercontent.com/29687965/135990223-6f70fc92-9749-400c-9471-b844a0af2635.png)

In livewire-component it has entry available too.

![image](https://user-images.githubusercontent.com/29687965/135990355-0a32d933-28e2-45a8-b6ba-f0cd655e3e04.png)

**Comment by Gustavinho** [comment]
thanks again @var2611 , and again, sorry for the late response, I'm glad you were able to solve it, I'll close this issue
