### ISSUE TITLE
Row with a relation data

### ISSUE THREAD

**Issue by muhammedshiffin** [Gustavinho/laravel-views#141]
Am trying to get a related data fetched but does not seem to work

```
User::class

hasOne(Number::class)
```

on the table

```
function row

return [
$model->number->extension
]
```

am I missing something?

**Comment by Gustavinho** [comment]
Hi @muhammedshiffin sorry for the late response, this seems like a problem in the relationship definition, is that number already created in the database?

**Comment by muhammedshiffin** [comment]
yes, it is created.
Am trying it again on a fresh project. I'll update you soon.

**Comment by Gustavinho** [comment]
Please let me know how else can I help
