### ISSUE TITLE
Documentation about filters and actions is not found

### ISSUE THREAD

**Issue by elfeffe** [Gustavinho/laravel-views#143]
I think the docs for actions, and filters, have dissapeared.

**Comment by Gustavinho** [comment]
Hi @elfeffe, is there a broken link? i'm seeing this docs https://github.com/Gustavinho/laravel-views/blob/master/doc/table-view.md#filters and https://github.com/Gustavinho/laravel-views/blob/master/doc/table-view.md#actions

**Comment by elfeffe** [comment]
Hi @Gustavinho 
Yes, this one https://github.com/Gustavinho/laravel-views/blob/master/doc/doc/table-view.md
Found here https://github.com/Gustavinho/laravel-views/blob/master/doc/laravel-views.md

**Comment by Gustavinho** [comment]
I noticed I never clicked the `Comment` button, I'm so so so so so sorry I didn't follow up, you're right those links are broken, I've been working on a documentation web page to be included in laravelviews.com, I'll release it soon, in the meantime I'll fix these broken links

**Comment by Gustavinho** [comment]
The documentation was moved to https://laravelviews.com/ last year and, the doc files have been finally removed from this repo
