### ISSUE TITLE
Not able to use <x-badge> in views.

### ISSUE THREAD

**Issue by var2611** [Gustavinho/laravel-views#144]
Hi,

I've tried install tailwind css (Basically), and also for laravel from it's guidline.

Performed all steps but not able to use that function, so is there any additional way did you performed?

Currently I'm using {{ variants('badges.'. $type) }} from table view as a work around.

**Comment by Gustavinho** [comment]
Hi @var2611 if you can use the `badge` component directly in other blade files after installing this package, there isn't a shortcut for this component (I should add it) but you can render it using the full namespace `<x-laravel-views::badge type="success" title="Hello I'm a badge" />`, however, if you can use it from a table view or another data view in this package, you should use it in your PHP class like this https://github.com/Gustavinho/laravel-views/blob/master/doc/table-view.md#badges

**Comment by var2611** [comment]
Okay I'll try this way, and yes from class file `UI::badge()` workes perfectly fine.
