### ISSUE TITLE
Inline Editing does not show updated value

### ISSUE THREAD

**Issue by hadesunseenn** [Gustavinho/laravel-views#146]
When we click on any column value and edit and then hit enter, the value in DB gets updated but when we click outside of updated input it shows old value, it should show a new updated value. Just like in jQuery Datatables. On page reload we can see the latest value.
The documentation site has the same error also

https://drive.google.com/file/d/1yhkjOXeGWRHpdtE2dFN4A4fkw0h71LjM/view

added a short video

**Comment by Gustavinho** [comment]
Thanks for raising this issue, I'll fix it

**Comment by Gustavinho** [comment]
Hello @hadesunseenn this has been fixed in [v2.4.1](https://github.com/Gustavinho/laravel-views/releases/tag/v2.4.1), I also updated the package in https://laravelviews.com/ to fix the examples
