### ISSUE TITLE
Customize localization

### ISSUE THREAD

**Issue by roomdada** [Gustavinho/laravel-views#154]
Good evening everyone can someone help me by showing me how to translate the localization of the package in French
![Capture d’écran du 2022-05-24 20-30-41](https://user-images.githubusercontent.com/61591337/170126855-5c74061c-383b-4cf3-bceb-95c7bfc19f19.png)
![Capture d’écran du 2022-05-24 20-30-41](https://user-images.githubusercontent.com/61591337/170126773-e709114a-985e-4404-b22b-96d1fca652c8.png)

**Comment by gyroid** [comment]
Did you do it?
