### ISSUE TITLE
Error: Unable to find the action

### ISSUE THREAD

**Issue by gyroid** [Gustavinho/laravel-views#155]
I create Laravel project using 

curl -s "https://laravel.build/example-app" | bash

I installed Jetstream with LiveWire.
I installed LaraveViews using this instruction https://laravelviews.com/installation

When I add sorting to Table View in this way:

Header::title('Name')->sortBy('name'),

the view render ok. When I click in sort arrow, the modal is show. After click "Yes, I'm sure" I have error: "Unable to find the action". It looks like the action is empty or null.

Has anyone any idea what I did wrong?

The same problem I have with search option.

Used version of packages:

        "php": "^8.0.2",
        "guzzlehttp/guzzle": "^7.2",
        "laravel-views/laravel-views": "^2.4",
        "laravel/framework": "^9.19",
        "laravel/jetstream": "^2.10",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.7",
        "livewire/livewire": "^2.5"

I found reason. In dev mode, I had import Tailwind/Livewire/AlpineJs and import LaravelViews using 
@laravelViewsStyles
@laravelViewsScripts

I changed to 
@laravelViewsStyles(laravel-views)
@laravelViewsScripts(laravel-views)
and everything is ok.

Maybe it will help someone.

**Comment by Gustavinho** [comment]
Thank you @gyroid for raising this and also for updating it with the fix, actually there was another open issue with exactly the same behavior and this will also help to solve it, thank you
