### ISSUE TITLE
XSS Bug

### ISSUE THREAD

**Issue by vdvcoder** [Gustavinho/laravel-views#158]
In the table view where you can edit inline there is a XSS vulnerability.

![image](https://user-images.githubusercontent.com/13916116/186617530-7d394488-7d8f-4bae-b61e-c61a24bd6c92.png)

**Comment by Gustavinho** [comment]
Hi @vdvcoder, what a great finding, although you can always validate the data on the server side, I think was executed on the client side, I'll take a loot at it to work on a fix, thanks

**Comment by Gustavinho** [comment]
Hello @vdvcoder  this has been fixed in [v2.4.1](https://github.com/Gustavinho/laravel-views/releases/tag/v2.4.1) thanks to @MKaczkow,  I also updated the package in https://laravelviews.com to fix the examples
