### ISSUE TITLE
vendor:publish --tag=views --provider='LaravelViews\LaravelViewsServiceProvider' not work to all, including master layout, to directory.

### ISSUE THREAD

**Issue by dfikeda** [Gustavinho/laravel-views#160]
Hello, I try copy files with the `php artisan vendor:publish --tag=views --provider='LaravelViews\LaravelViewsServiceProvider'` but this emit an error: ` No publishable resources for tag [views].`.
I publisheb by `php artisan vendor:publish` and selected "views" to copy the folder.
The copy not bring me a master layout to customize that.
(Suggested revision)
I suggest a revision of the package to laravel 9 (when its provide by default the Tailwind and Alpine, and its not necessary more from the package and another header link do css file.
Congrats to this package. Sorry about my english rsrs.

**Comment by dfikeda** [comment]
I copied manualy the folder resource [...] views/view to published resource vendor folder and its works.

**Comment by Gustavinho** [comment]
Hi @dfikeda, it's so good you were able to solve it

don't worry about your English, I understood perfectly, I speak Spanish as my native tongue so I'm still practicing

**Comment by Gustavinho** [comment]
Hi @dfikeda, I'll close this issue, thank you for posting it
