### ISSUE TITLE
UI::icon don't work properly

### ISSUE THREAD

**Issue by dfikeda** [Gustavinho/laravel-views#161]
After this [issue ](https://github.com/Gustavinho/laravel-views/issues/160) I have another issue about links to files.
`UI::icon` was not working properly, I noticed in the browser inspector that the html was rendered but the icon was not. I went to inspect the code and it pointed to the folder `vendor/laravel-views.css` and .js respectively and the files weren't there.
I believe it is a pointing error.
I made the fix by copying the mentioned files to the package folder to the public/vendor/ folder.

**Comment by Gustavinho** [comment]
Hi @dfikeda sorry for the late response, the workaround is fine however [publishing the assets](https://laravelviews.com/installation#publishing-assets) should do the same, did you do this?

**Comment by dfikeda** [comment]
Yes and I get the response:  "No publishable resources for tag [public]".

**Comment by Gustavinho** [comment]
I hadn't seen that problem before, could you share a little bit more about how you're publishing the assets?

I ran this test in a Laravel 9 project
<img width="889" alt="Screen Shot 2022-09-26 at 20 39 40" src="https://user-images.githubusercontent.com/4228757/192411479-0ca02db0-373c-46cd-8d38-dfbee909822a.png">

And the icons worked fine in this test
<img width="1032" alt="Screen Shot 2022-09-26 at 20 40 16" src="https://user-images.githubusercontent.com/4228757/192411513-67387db8-4323-493f-9871-c6d7b593c316.png">

**Comment by jmostro** [comment]
Hi Gustavinho, 
I'm having the same issue as dfikeda.
In this case I am running laravelviews on laravel 8, could be that the issue?

![image](https://user-images.githubusercontent.com/82106396/207873856-8512a4b3-26e5-4d43-89c9-13d7f1375d89.png)

**Comment by Gustavinho** [comment]
Hi @jmostro, sorry for the late response, yeah I was able to publish it as well on a brand new project with Laravel 8

<img width="888" alt="Screenshot 2022-12-19 at 16 17 53" src="https://user-images.githubusercontent.com/4228757/208537638-087a7b27-6a96-4c81-9eaf-d64e4fd2d347.png">

So is everything good then?

**Comment by jmostro** [comment]
Hi @Gustavinho, sure, had to use `php artisan vendor:publish`  command, and then select the tags from the menu, but it's working fine for me now!

Thanks for your reply!
