### ISSUE TITLE
Visibility of columns

### ISSUE THREAD

**Issue by kalwinskidawid** [Gustavinho/laravel-views#165]
Is it possible to hide columns? Is it always statically defined when first rendered?

**Comment by Gustavinho** [comment]
Hello @kalwinskidawid, there's no way to hide columns dynamically, there are defined statically

**Comment by kalwinskidawid** [comment]
Ouhh,
 It's a pity, do you plan to add such functionality?

**Comment by Gustavinho** [comment]
Hi @kalwinskidawid, I wasn't planning to add something like this, but thinking it through, it is actually a good idea, I will add it to the roadmap, thank you for the suggestion

**Comment by kalwinskidawid** [comment]
Awesome! Thanks 😄

**Comment by christoferd** [comment]
Isn't this straight forward to do manually?
Add properties to the calendar component such as: $showIdColumn, $showTitleColumn, ...
Then add a filters box to the top of the table where each field has a tick-box. The tick-box being _wired_ to a property.
Then could do wire:click="clickFilterOption" to call that function in your component.
Update the events accordingly.

Would this be the way to go about it until it's included in this source?

**Comment by Gustavinho** [comment]
Hi @kalwinskidawid I'll close this issue since I just added it to the roadmap
