### ISSUE TITLE
How can I make rows clickable to redirect to a URL?

### ISSUE THREAD

**Issue by christoferd** [Gustavinho/laravel-views#168]
Hi, Is there a way to make rows clickable to redirect to a _dynamic_ URL?

e.g. something like this...
```
->setTableRowUrl(function($row) {
    return route('clients.show', $row->id);
});
```

**Comment by Gustavinho** [comment]
Hi @christoferd clickable rows are not supported, however, you can render a link as part of the data like this https://laravelviews.com/ui-components#link

```php
UI::link($model->name, '/route')
```
