### ISSUE TITLE
Error messages appear as green success

### ISSUE THREAD

**Issue by christoferd** [Gustavinho/laravel-views#169]
Hi Error messages appear as green success.

laravel-views Config is default.

DeleteUserAction.php
```php 
$this->error(__('Not allowed to delete this record.'));
```

What I see:
![2022-12-23 08_57_53-Precio_Calc_App - Brave](https://user-images.githubusercontent.com/1835883/209332641-61f8d715-d586-4f76-b60b-72cf5946e9bc.png)

I can't test ```$this->setMessage('danger', $message);``` because the method is set to private. (Why private?) >.<

Versions
![image](https://user-images.githubusercontent.com/1835883/209333195-f4c5e83d-262d-4a71-8eea-8472a1957bd5.png)

PHP 8.1.13

How can I troubleshoot this?
The code looks to be using config to set classes but it still looks green.

**Comment by Gustavinho** [comment]
Hi @christoferd thanks for rasing this issue, I have taken a look at this and it is definitely a bug, let me work on a fix and I'll be pushing a new version this week

**Comment by Gustavinho** [comment]
Hello @christoferd this has been fixed in [v2.4.1](https://github.com/Gustavinho/laravel-views/releases/tag/v2.4.1), I also updated the package in https://laravelviews.com to fix the examples
