### ISSUE TITLE
Adding an optional confirmation modal for actions. 

### ISSUE THREAD

**Issue by fawzanm** [Gustavinho/laravel-views#17]
It would be great to have a confirmation modal for *dangerous* actions. Maybe we can take an additional parameter for the action and load a component with a confirmation message. 

May be we can have a default confirmation message like "Do you really want to perform the action?" and let the user override the title and message (or the entire view).

**Comment by Gustavinho** [comment]
yes you're right, it is in the roadmap for v1.2, you will be able to add this confirmation message to before executing the action
