### ISSUE TITLE
Issue when having two redirect actions in the same row

### ISSUE THREAD

**Issue by fawzanm** [Gustavinho/laravel-views#18]
I tried adding two redirect action for a row, one for `view` and another one for `edit`. Both of the resolves to the same route for the `view` redirect action. When I try the `edit` one alone, it resolves to the correct route. 

```
 new RedirectAction('user', 'See user', 'eye'),
 new RedirectAction('user-edit', 'Edit user', 'edit'),
```

**Comment by fawzanm** [comment]
I believe I figured out the reason for this, `$id` for the action is generated using the class name. Not sure how best we can solve it or whether it's worth doing it.

**Comment by Gustavinho** [comment]
Hey thanks for raising this issue, even if the id is the same the actions spouse to be different between them, I'm gonna take a look at it this weekend and lets hope to have a hotfix for this

**Comment by Gustavinho** [comment]
I pushed a new version with this hotfix, you were right, it was because of the id
