### ISSUE TITLE
Confirm modal message not working

### ISSUE THREAD

**Issue by sabaw123** [Gustavinho/laravel-views#185]
![image](https://user-images.githubusercontent.com/121992898/210689947-cd0ce082-2e29-4fc7-a4ee-ea6ff499a999.png)

I have Delete action button by row, and when click on it there nothing happen when I use the Confirmable class traits, but when I remove use Confirmable; the delete action continue without confirmation, My goal is to use the confirmation modal before continuing the delete process. This is my app.blade. I'm using Laravel 9

![image](https://user-images.githubusercontent.com/121992898/210689507-ccaae290-3dea-4eca-acc4-44fd35433064.png)
![image](https://user-images.githubusercontent.com/121992898/210689544-4706fcfd-8efe-4412-9f60-e63c29cec713.png)

my app.js:
![image](https://user-images.githubusercontent.com/121992898/210689684-c9cb8512-0f18-42d2-8364-57f66346d79d.png)

**Comment by sabaw123** [comment]
Thanks for the reply. Still the same  when I remove @stack('modals') . but when I removed laravel-views in @laravelViewsScripts(laravel-views) it shows the modal but when I click 'Cancel' or "Yes I'm Sure" its not closing the modal. And even I'm not using Confirmable traits it always display on other actions and just even I refresh the table.
![image](https://user-images.githubusercontent.com/121992898/210907585-a12ec8fc-af0e-43fa-85fc-53282e0f1e8b.png)

This is the response in network
![image](https://user-images.githubusercontent.com/121992898/210907840-7c2f4600-fea0-4c3a-a873-8e4ce5f397c3.png)

This is the payload
![image](https://user-images.githubusercontent.com/121992898/210907880-54d5ff79-9c25-4bea-857a-f802e894d196.png)


Thanks in advance.

**Comment by sabaw123** [comment]
Already resolve it. I'm not sure if the livewire or alpine js are conflict. But I just add alpine in
`@laravelViewsScripts(laravel-views, alpine)`  . Thank you

**Comment by Gustavinho** [comment]
thank you @sabaw123, I'll take a look at the exact versions of the different components of the stack
