### ISSUE TITLE
Searching on relationship

### ISSUE THREAD

**Issue by fawzanm** [Gustavinho/laravel-views#31]
Hi @Gustavinho 

I have been playing around with the search feature in the table when we want to search in a relational field. I can send a PR but before that, I want to get your opinion.  

Let's take a simple case. 

```
-> posts database table
id | user_id | title | content
```

Let's say we have a `TableView` for the `posts` table, where I list the post table in the following way. 
```
id | title | author_name
```

Currently, I can only search with the fields in the model, but I also want to search with the `author_name`.  My current solution is as follows

```
    public $searchBy = ['id', 'user.name'];
```

and I have modified the `searchItems` as follows. 

```
public function searchItems(Builder $query, $fields, $value): Builder
    {
        $relationalFields = array_filter($fields, fn($item) => str_contains($item, '.'));
        $regularFields = array_filter($fields, fn($item) => !str_contains($item, '.'));

        if ($value) {

            $query->where(function ($query) use ($value, $regularFields, $relationalFields) {

                foreach ($regularFields as $field) {
                    $query->orWhere($field, 'like', "%{$value}%");
                }

                foreach ($relationalFields as $relationalValue) {
                    $keys = explode('.', $relationalValue);

                    $query->orWhereHas($keys[0], function ($query) use ($value, $keys) {
                        $query->where($keys[1], 'like', "%{$value}%");
                    });
                }

            });


        }

        return $query;
    }
```

Please let me know if you see any issue or can think of any edge cases where it would fail. I can send a PR to `1.1` with the updates.

**Comment by Gustavinho** [comment]
Hey hi, I really like this approach, I was thinking in something like `user.name` as well but I hadn't think about the implementation yet, I think yours is great, just please take a look at this:

- Turn your PR as draft until it is ready
- Dont push code using PHP 8 yet, I think there could be a lot of systems which are not using PHP 8
- We have to include a test case for this (the setup to use migrations, factories etc is currently there)
- you could use destructuring assignment on the `$relationalValue`
- Change the documentation to explain this
- If you notice that your implementation is too large, you can create another method on the `TableViewSearchData` class and the `Searchable` interface, with that, the `Searchable` interface will make us know how to implement regular queries and relational queries

As the `GridView` extends of `TableView` this feature will work out with the grid as well.

What a great feature 👍

**Comment by fawzanm** [comment]
Hi @Gustavinho 

Thanks for the detailed response. I will adhere to the above comments and send the PR. I have a couple more questions though. 

1. What's the minimum supported version of PHP for the package? 
2. Which branch should I send the PR too?

**Comment by Gustavinho** [comment]
> Hi @Gustavinho
> 
> Thanks for the detailed response. I will adhere to the above comments and send the PR. I have a couple more questions though.
> 
> 1. What's the minimum supported version of PHP for the package?
> 2. Which branch should I send the PR too?

**Comment by Gustavinho** [comment]
I've tested it with PHP 7.1, 7.2 and 7.3, I might add test cases for 7.4 as well, and about the PR I think `release-1.1.0` is fin as you said
