### ISSUE TITLE
Laravel-views styles overwriting tailwind extended fonts

### ISSUE THREAD

**Issue by dircm** [Gustavinho/laravel-views#43]
If @laravelViewsStyles is used in projects with tailwind extensions, the browser will ignore any extended fonts and use the styles from laravel-views.

In laravel-views.css, the following style is present:

`html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;line-height:1.5}`

This will overwrite any other HTML font that is included in tailwind.

Do the primitives fonts need to be included in the laravel-views.css at all?  Maybe remove and favour importing styles and fonts as needed (like pickaday etc) with style imports ?

**Comment by Gustavinho** [comment]
Hi @dircm thanks for raising this issue, it is always using the default tailwindcss setup thinking in those projects which are not using tailwind, but I might should add an option to the @laravelViewsStyles in order to no don't include the tailwindcss styles, so we can use our own tailwindcss setup, what do you think? would it work out?

**Comment by dircm** [comment]
Hi thanks for the update, my thoughts are that this project should only include the styles and scripts required to get functioning.  I also would like to keep the livewire scrips and styles separated as well.  I imagine most tailwind based sites will have webpack installing the styles into app.css / js anyway.

Perhaps you can include the basic required styles and scripts in your repo alongside the current includes so the developer can decide on what level of include they need ? 

Thanks and nice work.  Tom.

**Comment by Gustavinho** [comment]
Hi Tom, I think this is a good approach, being able to decide what we want to include, I'm gonna take a look on this to have this feature as soon as I can.

Thanks again

**Comment by santhika29** [comment]
@dircm may be u can use @laravelViewsStyles before declare the default font, it works for me
