### ISSUE TITLE
UI::avatar() can set custom size?

### ISSUE THREAD

**Issue by JulioCGMC** [Gustavinho/laravel-views#55]
Hy, i`m using your plugin to extends my laravel project and i display an image on my table, do u know a way to change the size of the UI::avatar() class?

**Comment by Gustavinho** [comment]
Hi @JulioCGMC , you could publish the config file, there is an array to customize some components variants like avatar, an avatar is a variant of an image,  

```
"images" => [
    'avatar' => 'h-8 w-8 object-cover rounded-full shadow-inner'
],
```

unfortunately there isn't a way yet to customize the UI::avatar() directly on the UI class.

**Comment by JulioCGMC** [comment]
Thanks, i have yet another question, there is a way to send a custom query?
For instance, i want to show a table with all the galeries for a specific category, theres a way to send the category_id for that Gallery::query(), or send the query already?
