### ISSUE TITLE
How to send custom data or custom query

### ISSUE THREAD

**Issue by JulioCGMC** [Gustavinho/laravel-views#56]
Thanks, i have yet another question, there is a way to send a custom query?
For instance, i want to show a table with all the galeries for a specific category, theres a way to send the category_id for that Gallery::query(), or send the query already?

_Originally posted by @JulioCGMC in https://github.com/Gustavinho/laravel-views/issues/55#issuecomment-704410938_

**Comment by Gustavinho** [comment]
Hi @JulioCGMC, this is a good question, I don't have a way to send parameters natively with the render method, but at the end, the render method is calling the `@livewire` blade directive, so you could use the directive `@livewire` to send more params like this `@livewire(App\Http\Livewire\MyTableview, ['category_id' => $category->id])`. To get this value in your PHP class you could define it as a public property `public $category->id` and you could use it to set your query return MyModel::where('category_id', $this->category_id);`, that should work.

Please let me know if this works for you, I'm thinking to add this feature natively anyway.

**Comment by JulioCGMC** [comment]
Se fosse possivel seria otimo, muito mesmo, mas vou tentar desta forma enquanto isso, valeu
[If possible, would be great, for real, but for now i`ll try that way, thanks]
