### ISSUE TITLE
[question] display boolean value

### ISSUE THREAD

**Issue by santhika29** [Gustavinho/laravel-views#57]
hai, im new in laravel... i wanna ask about how to display yes/no or active/not active with badge for boolean value like in your image??
sorry for my silly question

**Comment by Gustavinho** [comment]
Don't worry about it, there aren't silly questions, you could just ask for the boolean value and rendering one badge or the other, something like `$model->active ? UI::badge('yes', 'success') : UI::badge('no', 'danger')`

**Comment by santhika29** [comment]
thank u pal
