### ISSUE TITLE
Click actioning makes icon dissappear

### ISSUE THREAD

**Issue by eugenevdm** [Gustavinho/laravel-views#59]
Whenever I click an action the icon disappears....is there a way to make it sticky?

**Comment by Gustavinho** [comment]
Hi @eugenevdm By any chance are you using an unexisting feather icon? I remember this happened to me before

**Comment by eugenevdm** [comment]
Hi @Gustavinho apologies for the slow reply. I finally managed to do a deep dive. You are right, something weird about the feather icons. To isolate, I completely removed the actions and just implemented search:

When the page loads, the search up / down arrows are there and working and they are pure SVGs:

```html
<th class="px-3 py-3">
    <div class="flex">
        <a href="#!" wire:click.prevent="sort('verification_status')" class="flex-1">Status</a>
        <a href="#!" wire:click.prevent="sort('verification_status')" class="flex">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-up text-gray-900 h-4 w-4"><polyline points="18 15 12 9 6 15"></polyline></svg>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down text-gray-400 h-4 w-4"><polyline points="6 9 12 15 18 9"></polyline></svg>
        </a>
    </div>
</th>
```

Then the moment you click on sort, the HTML changes to this, and the icons are missing:

```html
<th class="px-3 py-3">
    <div class="flex">
        <a href="#!" wire:click.prevent="sort('verification_status')" class="flex-1">Status</a>
        <a href="#!" wire:click.prevent="sort('verification_status')" class="flex">
            <i data-feather="chevron-up" class="text-gray-400 h-4 w-4"></i>
            <i data-feather="chevron-down" class="text-gray-900 h-4 w-4"></i>
        </a>
    </div>
</th>
```

Sort does however work, just the HTML has changed and one cannot see the icon.

Any clues where to look next? :-)

**Comment by eugenevdm** [comment]
Update :-) Found the issue:

https://github.com/livewire/livewire/issues/1083

Do this:

```html
<span wire:ignore>
    <i data-feather="chevron-up" class="{{ $sortBy === $header->sortBy && $sortOrder === 'asc' ? 'text-gray-900' : 'text-gray-400'}} h-4 w-4"></i>
</span>
```html

**Comment by Gustavinho** [comment]
Great @eugenevdm !!!, yeah thanks, feel free to send the PR, i hadn't seen this behavior with the sort icons before but this will help.

**Comment by eugenevdm** [comment]
Hi again @Gustavinho ,

I made the pull request https://github.com/Gustavinho/laravel-views/pull/60 but checks are failing that seems unrelated to the addition of those `<span>` tags. The pull request seems to fail due to PHP versioning issue, and Travis also seems to fail due to PHP versioning issue. Not sure how to fix either!

**Comment by Gustavinho** [comment]
Hi @eugenevdm don't worry about it, I can take a look at it tomorrow and try to fix it, it seems there is a deprecated phpunit function

**Comment by petr5250** [comment]
Hi, I've managed to work around the issue by using Laravel 8 dynamic components and [brunocfalcao/blade-feather-icons](https://github.com/brunocfalcao/blade-feather-icons).
Here is the example of components/buttons/icon.blade.php file:

```html
@props(['icon', 'size' => 'md'])

<button {{ $attributes }} class="{{ $size === 'sm' ? 'p-1' : 'p-2'  }} border-2 border-transparent text-gray-500 rounded-full hover:text-gray-300 focus:outline-none focus:text-gray-500 focus:bg-gray-100 transition duration-150 ease-in-out">
  <x-dynamic-component :component="'feathericon-' . $icon" class="{{ $size === 'sm' ? 'w-5 h-5' : ''  }}"/>
</button>
```

**Comment by Gustavinho** [comment]
Great @petr5250 , I've been tempted to use `<x-dynamic-component />` but the package is supporting Laravel 8 too, I have a custom dynamic component and I didn't know about the `blade-feather-icons`, I'll take a loot at it, btw, I've not replicated this behavior yet, what do you do to see this bug?
