### ISSUE TITLE
Defult value for filter?

### ISSUE THREAD

**Issue by elfeffe** [Gustavinho/laravel-views#80]
Is it possible to set default value for a filter?

**Comment by Gustavinho** [comment]
Hi @elfeffe sorry for the late response, unfortunately, it is not supported yet but that is a great idea, I will add it to the roadmap

**Comment by elfeffe** [comment]
Another idea is to offer to search using Scout, not just MySQL.
That will useful for grid and list view

**Comment by Gustavinho** [comment]
That is another great idea, I love it, I had not even thought about it, I added it to my backlog, thanks again

**Comment by Gustavinho** [comment]
Hi @elfeffe, your PR to add default value for filters was merged to the `release/2.3.0` some weeks ago and now it is almost ready to be released, I'm just running some final tests to release it but there is already an RC version

**Comment by Gustavinho** [comment]
Hi @elfeffe, I released the feature with the default value for filters, I'll close this issue
