### ISSUE TITLE
Bulk actions

### ISSUE THREAD

**Issue by elfeffe** [Gustavinho/laravel-views#81]
Any plan to add bulk actions?

**Comment by Gustavinho** [comment]
Hi @elfeffe, actually yes I have plans to add bulk actions soon, to all of the data views

**Comment by elfeffe** [comment]
@Gustavinho How to use actions? The docs have Error 404

**Comment by Gustavinho** [comment]
Hi @elfeffe You're right I just fixed the ListView and GridView docs, either way here's the link [https://github.com/Gustavinho/laravel-views/blob/master/doc/table-view.md#actions](https://github.com/Gustavinho/laravel-views/blob/master/doc/table-view.md#actions)

**Comment by Gustavinho** [comment]
Hi @elfeffe I finally was able to add bulk actions to the table, list, and grid view. I'm just running some final tests to release this

**Comment by Gustavinho** [comment]
Hi @elfeffe, I released the bulk actions feature, I'll close this issue
