### ISSUE TITLE
Is it possible to use a Illuminate\Database\Query\Builder (rather than Eloquent)?

### ISSUE THREAD

**Issue by orware** [Gustavinho/laravel-views#86]
I am going to try and create some models next here on my end and push through trying to get some output on the screen here with Laravel Views, but just wanted to bring this up as one potential discussion item.

Sidebar: In my current background/experience, I've generally struggled with using ORMs and instead relied a lot more on creating my own SQL queries with the joins and filters I need (for several reasons...since I'm familiar with SQL though, it's easier for me to develop my query separately usually and then having to then translate it into an ORM format isn't always straightforward...then down the road when a tweak is made, sometimes adding things to an ORM version of the query isn't straightforward so I might need to export the query to a string so I can work with it in SQL directly). 

This need in particular is even more complex when I talk about interacting with our Oracle database directly (since that database has hundreds/thousands of tables and some of our queries can be hundreds of lines long at times or have complex joins in them and creating Model classes and rewriting a lengthy SQL query provided by a colleague isn't desirable).

For that reason, I was starting my tests with Laravel Views with the following query:

```php
    public function repository(): Builder
    {
        return DB::table('courses')
                    ->where('term_code', $this->term)
                    ->where('row_status', 'A');
    }
```

But received an error because the code is expecting a `Illuminate\Database\Eloquent\Builder` instance instead (I tried switching the use statement to `Illuminate\Database\Query\Builder` but some code further in was also expecting the Eloquent Builder too so it doesn't seem like I can use the Database Query Builder class).

At the moment, is it a current limitation of Laravel Views that I must have associated model classes? If so, that's ok for now (I'll work on adding some models next on my end).

**Comment by Gustavinho** [comment]
Hi @orware 

Yeah all the data views are using models and Eloquent so you can get the model instances in your actions or other parts of the code rather than receiving id's or array so you can keep using your model and all the methods and business logic in your model without creating it manually
