### ISSUE TITLE
Filter Positioning (When Not Using Search Feature)

### ISSUE THREAD

**Issue by orware** [Gustavinho/laravel-views#87]
I started first by adding in a filter to try that out, but I noticed it did something a bit odd I didn't notice on the demo site.

When making my browser window smaller,, I noticed the filter icon ended up moving to the left of the page as I got closer to a mobile width.

This caused a few issues, but mainly the issue was that since it was over on the left-hand side, when the filter area was opened most it was cutoff so you couldn't actually see it correctly.

I noticed all of the demo examples are including the search and filters so the problem isn't present in that situation, but hopefully some small tweaks can be made that would help keep the filters area off to the right-hand side even when not using the search feature to help keep it usable.

**Comment by Gustavinho** [comment]
Hi @orware 

You're right, nice catch I'll fix this

**Comment by Gustavinho** [comment]
Hi @orware this was fixed https://github.com/Gustavinho/laravel-views/pull/98
