### ISSUE TITLE
Complex Filtering Requirements + Multiple Selection Dropdown Filter

### ISSUE THREAD

**Issue by orware** [Gustavinho/laravel-views#89]
I'm going to see if I can maybe implement the filter  I'd like multiple selection for as a boolean filter instead (since that's implemented as a checkbox, I think it should provide the expected behavior), but I did want to bring up the possibility of having a multiple select dropdown filter option where more than one item could potentially be selected at one time.

The other part of this request it also related to situations where there are going to be complex filtering needs where using the search option isn't going to be that desirable (at least at the moment I'm not planning on making use of the search feature, but that may change).

If I switch to using the boolean filter approach on my end, I'm going to have some long lists to deal with for the filters (hundreds of instructors in one case, about a hundred rooms in another, etc.).

Since I haven't created the filters yet, I'm imagining that they may end up looking a bit weird at the end of the process (the filter area will be pretty long and narrow) so I'm not sure if displaying it in a modal (maybe where it can expand to display things in multiple consistent height columns more easily) might be an option that could be turned on in certain cases just to help with the way things look.

I'll update this one with my experience once I've created the filters though and have a better idea as to how it looks.

**Comment by Gustavinho** [comment]
Hi @orware 

I like the idea to have a filter with a select with multiple selection, I think it is worth it to include this filter

About the complex filter, not sure how could I tackle this, maybe adding the flexibility for us as devs to build our own filters,  not just using the pre-built ones, with that, we could build any filter we want, and maybe they could be displayed in a different way than the default dropdown, it could be a modal, a drawer or another UI element
