### ISSUE TITLE
Potential Search Results Improvement Idea

### ISSUE THREAD

**Issue by orware** [Gustavinho/laravel-views#90]
At the moment, I'm not sure how in depth users of the package are getting with their search implementations, but one thing I noticed relatively quickly is that it does appear to make use of the entire provided search term exactly for the columns specified, which doesn't always lead to the best result (although this might be the preferred behavior so this next idea might be an option that can be configured).

Here's an example: I have a list of courses and have the `subject` (e.g. let's say CS for Computer Science) and `course_number` (e.g. 100, 101, 200, etc.) enabled in the `$searchBy` property.

Over on my page, if I try and search for a valid combination (e.g. "CS 100") I currently would get zero results, because the search currently uses the entire phrase and tries to see if there is a value that matches it, but since there isn't when searching like this, we get the zero results.

If instead, the search functionality took the search phrase and split it in on each space and ran each of those words into the search, we would first get a list of all "CS" courses, and then would filter that list by all of those that have "100" in them, which might be a bit more accurate (as far as the user's intentions anyway) if it's possible to do something like that.

I think another item possibly related to this situation (and I don't have an answer for it at the moment based on the documentation I've read so far), is whether or not Laravel Views allows for additional custom attributes to be included (e.g. this may be related to this functionality available in Laravel Models: https://laravel.com/docs/8.x/eloquent-mutators but let's say in a custom SQL situation, I could take the `subject` and `course_number` columns mentioned above and concatenate them into a new column to bring in my results...if that column were included in the `$searchBy` property then it could be searched directly as an extra option instead of the suggestion I had above to split the search phrase into words).

**Comment by Gustavinho** [comment]
Hi @orware 

Yeah the default behavior of the `searchBy` is to take the entire text and run the query over all the fields specified using that text, the search also supports relational search, and I think it could be a great feature to add concat queries, e.g. it is pretty common to have `name` and `last_name` in different fields so with the current behavior you wouldn't be able to search users by full name concatenating the fields.

Either way, you can create your own implementation of the search query, it is not documented (yet) but that is how it works.

You can create a class implementing the `LaravelViews\Data\Contracts\Searchable` interface and binding it to your implementation in the `AppServiceProvider`

```
$this->app->bind(Searchable::class, MyCustomizedSearchData::class);
```

The data view will use the `MyCustomizedSearchData::class` query on the search input, I've had some cases where I've had to create customized queries for some customers and this approach has been helpful in those cases
