### ISSUE TITLE
Action Notification blocks actions

### ISSUE THREAD

**Issue by elfeffe** [Gustavinho/laravel-views#95]
It blocks the action buttons because of the position, I think the best is to have it always at bottom instead of:
`fixed z-50 bottom-0 left-0 w-full p-4 md:w-1/2 md:top-0 md:right-0 md:p-8 md:left-auto xl:w-1/3`

**Comment by Gustavinho** [comment]
You're right, thanks @elfeffe,  I'll try to keep it at top but I'll fix this this ASAP

**Comment by Gustavinho** [comment]
Hi @elfeffe this was fixed https://github.com/Gustavinho/laravel-views/pull/97
